In [2]:
import pandas as pd
import numpy as np

In [3]:
ak= pd.read_csv("iris.csv")
print(ak.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
ak.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [5]:
ak.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [6]:
ak.shape

(150, 5)

In [7]:
ak.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [8]:
ak['sepal_width']

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [9]:
ak.describe(include='all')

        sepal_length  sepal_width  petal_length  petal_width species
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.054000      3.758667     1.198667     NaN
std         0.828066     0.433594      1.764420     0.763161     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
25%         5.100000     2.800000      1.600000     0.300000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
75%         6.400000     3.300000      5.100000     1.800000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN

In [10]:
ak.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [12]:
ak.isnull()

     sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]

In [11]:
ak.isnull().any

<bound method DataFrame.any of      sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]>

In [12]:
ak['sepal_length'] = ak['sepal_length'].astype(int)

In [23]:
ak.dtypes

sepal_length      int64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [13]:
ak['sepal_length']

0      5
1      4
2      4
3      4
4      5
      ..
145    6
146    6
147    6
148    6
149    5
Name: sepal_length, Length: 150, dtype: int64

In [14]:
ak.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [16]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

ak[['sepal_length','sepal_width','petal_length','petal_width']] = scaler.fit_transform(
    ak[['sepal_length','sepal_width','petal_length','petal_width']]
)

print(ak.head())

   sepal_length  sepal_width  petal_length  petal_width species
0      0.333333     0.625000      0.067797     0.041667  setosa
1      0.000000     0.416667      0.067797     0.041667  setosa
2      0.000000     0.500000      0.050847     0.041667  setosa
3      0.000000     0.458333      0.084746     0.041667  setosa
4      0.333333     0.666667      0.067797     0.041667  setosa

In [18]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

ak['species'] = le.fit_transform(ak['species'])

print(ak.head())

   sepal_length  sepal_width  petal_length  petal_width  species
0      0.333333     0.625000      0.067797     0.041667        0
1      0.000000     0.416667      0.067797     0.041667        0
2      0.000000     0.500000      0.050847     0.041667        0
3      0.000000     0.458333      0.084746     0.041667        0
4      0.333333     0.666667      0.067797     0.041667        0